# Generated by Django 3.2 on 2023-06-05 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0003_auto_20230605_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinfo',
            name='bprice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
