# Generated by Django 3.2 on 2023-06-05 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0005_alter_bookinfo_bprice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='heroinfo',
            old_name='id_delete',
            new_name='is_delete',
        ),
    ]
