# Generated by Django 3.2 on 2023-06-06 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0008_area'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='area',
            table='areas',
        ),
    ]
